apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: echoserver
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: echoserver
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: docs/examples/echoservice/
    repoURL: https://github.com/kubernetes-sigs/aws-load-balancer-controller
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true   
    syncOptions:
    - CreateNamespace=true 
    retry:
      limit: 1
      backoff:
        duration: 5s 
        factor: 2 
        maxDuration: 1m
